# Generated by Django 2.2.7 on 2019-11-06 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20191106_1327'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Job',
            new_name='Blog',
        ),
    ]
